### PR TITLE
Add Typed Arrays support into ES6 lib

### PR DESCRIPTION
**Pull request by andruhon**

### CODE REVIEW

**Comment by unbornchikken** [comment]
Thanks. I think I'm gonna deprecate this module, because ES6+ made the whole idea obsolete. But by my opinion, the serializer is pretty good, I'm using it in my other projects. So I'm planning to create a separate serializer module, and deprecate this for good. What do you say?

**Comment by andruhon** [comment]
Sounds like a good idea!

**Comment by andruhon** [comment]
Hi! Could you please bump the minor version up and publish it to the NPM?

**Comment by unbornchikken** [comment]
It's done. Sorry for the delay.

**Comment by andruhon** [comment]
Cool! Thank you!

**Pull request merged**
